/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BookedPreviewRouteImport } from './routes/booked-preview'
import { Route as CheckoutPreviewRouteImport } from './routes/checkout-preview'
import { Route as LayoutPreviewRouteImport } from './routes/layout-preview'
import { Route as PhotoboothIndexRouteImport } from './routes/photobooth/index'
import { Route as ApiPublicPaymentsWebhookRouteImport } from './routes/api/public/payments/webhook'
import { Route as PhotoboothApiPublicPaymentsWebhookRouteImport } from './routes/photobooth/api/public/payments/webhook'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BookedPreviewRoute = BookedPreviewRouteImport.update({
  id: '/booked-preview',
  path: '/booked-preview',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutPreviewRoute = CheckoutPreviewRouteImport.update({
  id: '/checkout-preview',
  path: '/checkout-preview',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutPreviewRoute = LayoutPreviewRouteImport.update({
  id: '/layout-preview',
  path: '/layout-preview',
  getParentRoute: () => rootRouteImport,
} as any)
const PhotoboothIndexRoute = PhotoboothIndexRouteImport.update({
  id: '/photobooth/',
  path: '/photobooth/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPaymentsWebhookRoute =
  ApiPublicPaymentsWebhookRouteImport.update({
    id: '/api/public/payments/webhook',
    path: '/api/public/payments/webhook',
    getParentRoute: () => rootRouteImport,
  } as any)
const PhotoboothApiPublicPaymentsWebhookRoute =
  PhotoboothApiPublicPaymentsWebhookRouteImport.update({
    id: '/photobooth/api/public/payments/webhook',
    path: '/photobooth/api/public/payments/webhook',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/booked-preview': typeof BookedPreviewRoute
  '/checkout-preview': typeof CheckoutPreviewRoute
  '/layout-preview': typeof LayoutPreviewRoute
  '/photobooth/': typeof PhotoboothIndexRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
  '/photobooth/api/public/payments/webhook': typeof PhotoboothApiPublicPaymentsWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/booked-preview': typeof BookedPreviewRoute
  '/checkout-preview': typeof CheckoutPreviewRoute
  '/layout-preview': typeof LayoutPreviewRoute
  '/photobooth': typeof PhotoboothIndexRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
  '/photobooth/api/public/payments/webhook': typeof PhotoboothApiPublicPaymentsWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/booked-preview': typeof BookedPreviewRoute
  '/checkout-preview': typeof CheckoutPreviewRoute
  '/layout-preview': typeof LayoutPreviewRoute
  '/photobooth/': typeof PhotoboothIndexRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
  '/photobooth/api/public/payments/webhook': typeof PhotoboothApiPublicPaymentsWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/booked-preview'
    | '/checkout-preview'
    | '/layout-preview'
    | '/photobooth/'
    | '/api/public/payments/webhook'
    | '/photobooth/api/public/payments/webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/booked-preview'
    | '/checkout-preview'
    | '/layout-preview'
    | '/photobooth'
    | '/api/public/payments/webhook'
    | '/photobooth/api/public/payments/webhook'
  id:
    | '__root__'
    | '/'
    | '/booked-preview'
    | '/checkout-preview'
    | '/layout-preview'
    | '/photobooth/'
    | '/api/public/payments/webhook'
    | '/photobooth/api/public/payments/webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BookedPreviewRoute: typeof BookedPreviewRoute
  CheckoutPreviewRoute: typeof CheckoutPreviewRoute
  LayoutPreviewRoute: typeof LayoutPreviewRoute
  PhotoboothIndexRoute: typeof PhotoboothIndexRoute
  ApiPublicPaymentsWebhookRoute: typeof ApiPublicPaymentsWebhookRoute
  PhotoboothApiPublicPaymentsWebhookRoute: typeof PhotoboothApiPublicPaymentsWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/booked-preview': {
      id: '/booked-preview'
      path: '/booked-preview'
      fullPath: '/booked-preview'
      preLoaderRoute: typeof BookedPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout-preview': {
      id: '/checkout-preview'
      path: '/checkout-preview'
      fullPath: '/checkout-preview'
      preLoaderRoute: typeof CheckoutPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/layout-preview': {
      id: '/layout-preview'
      path: '/layout-preview'
      fullPath: '/layout-preview'
      preLoaderRoute: typeof LayoutPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/photobooth/': {
      id: '/photobooth/'
      path: '/photobooth'
      fullPath: '/photobooth/'
      preLoaderRoute: typeof PhotoboothIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/payments/webhook': {
      id: '/api/public/payments/webhook'
      path: '/api/public/payments/webhook'
      fullPath: '/api/public/payments/webhook'
      preLoaderRoute: typeof ApiPublicPaymentsWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/photobooth/api/public/payments/webhook': {
      id: '/photobooth/api/public/payments/webhook'
      path: '/photobooth/api/public/payments/webhook'
      fullPath: '/photobooth/api/public/payments/webhook'
      preLoaderRoute: typeof PhotoboothApiPublicPaymentsWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BookedPreviewRoute: BookedPreviewRoute,
  CheckoutPreviewRoute: CheckoutPreviewRoute,
  LayoutPreviewRoute: LayoutPreviewRoute,
  PhotoboothIndexRoute: PhotoboothIndexRoute,
  ApiPublicPaymentsWebhookRoute: ApiPublicPaymentsWebhookRoute,
  PhotoboothApiPublicPaymentsWebhookRoute:
    PhotoboothApiPublicPaymentsWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
